POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "123@gmail.com",
  "password": "qwe"
}

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "email": "1232wq@gmail.com",
  "password": "qwe"
}

###

POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json

{
  "event": "user.upgraded",
  "data": {
    "user_id": 1
  }
}

###

GET localhost:8080/api/chirps

